### ISSUE TITLE
mongo collection issue

### ISSUE THREAD

**Issue by mattiLeBlanc** [barbatus/typescript#10]
Hi,

I moved over from pbastowski's typescript package to yours since this one is going to be officially supported by the Meteor team.

I am running in a `ReferenceError: require is not defined` issue with my Mongo collections.

I am setting up the collections like this: https://github.com/pbastowski/meteor1.3-collection-import

Is this package not yet supporting Meteor 1.3?

**Comment by barbatus** [comment]
You'll have to install `modules` package https://atmospherejs.com/meteor/modules.

**Comment by mattiLeBlanc** [comment]
I thought Meteor 1.3 supported modules out of the box? When your plugin is assimilated it will automatically install `modules` as a dependency?

**Comment by barbatus** [comment]
if you create a new app with Meteor 1.3 it will add it by default.
If you upgrade your app by running `meteor update` Meteor will update `ecmascript` to include `modules`.

`modules` is based on CommonJS while TypeScript can be configured to render,  for example, SystemJS that's why it doesn't imply `modules` so far. You either have `ecmascript` by default and `typescript` installed if you want CommonJS, or  `systemjs` and `typescript` if want SystemJS.

**Comment by mattiLeBlanc** [comment]
Okay Roger

**Comment by mattiLeBlanc** [comment]
yes, it is working now.
I do get a lot of warnings in my console, like
```
imports/collections/invoices.ts (1, 23): Cannot find module 'meteor/mongo'.
server/methods/invoice.ts (2, 35): Cannot find module '/imports/collections/invoices'
```
while the in the invoices file I am exporting the collection:
```
import { Mongo } from 'meteor/mongo';
export var Invoices = new Mongo.Collection('invoices');
```

Also..the app is not showing any errors.
What am I doing wrong to upset the compiler? Any suggestions

**Comment by jacobdr** [comment]
Please see the issue https://github.com/barbatus/typescript/issues/6 to resolve module resolution issue with the new "meteor/*" namespace

**Comment by mattiLeBlanc** [comment]
I will have a look, thanks.

**Comment by jacobdr** [comment]
Let me know if you need any more help. Otherwise, remember to close the issue.

**Comment by mattiLeBlanc** [comment]
I am not sure if I am already doing what you suggested?

My typings file:
```
{
  "ambientDependencies": {
    "angular": "github:DefinitelyTyped/DefinitelyTyped/angularjs/angular.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1",
    "angular-meteor": "github:DefinitelyTyped/DefinitelyTyped/angular-meteor/angular-meteor.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1",
    "angular-ui-router": "github:DefinitelyTyped/DefinitelyTyped/angular-ui-router/angular-ui-router.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1",
    "jquery": "github:DefinitelyTyped/DefinitelyTyped/jquery/jquery.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1",
    "lodash": "github:DefinitelyTyped/DefinitelyTyped/lodash/lodash.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1",
    "meteor": "github:DefinitelyTyped/DefinitelyTyped/meteor/meteor.d.ts#e69fe60f2d6377ea4fae539493997b098f52cad1"
  }
}

```

and my tsconfig:
```
{

    "compilerOptions": {
        "module": "commonjs"
    },
    "compileOnSave": false,
    "buildOnSave": false

}

```

**Comment by jacobdr** [comment]
I don't think that the Meteor definitions have been updated for 1.3 quite yet. I created a Gist based on the great work of @tomitrescak, which is probably installed most easily with: 

`typings install --save --ambient meteor=https://gist.githubusercontent.com/jacobdr/6010b922d449e4aa1b001862f200e3ef/raw/d2baf474c271ff1c9d77961ae11750cdcbc30abb/meteor.d.ts`

Note: This is a temporary fix and I don't plan on maintaining it. I'm kind of waiting for official Meteor typings to come around...

**Comment by mattiLeBlanc** [comment]
okay, I will wait too then. It is not blocking us. Just throwing a lot of messages in the console.
Also about Import paths not being correct however the application is working fine.
Then when you update the paths to make the compiler happy, the application breaks.  lol!

**Comment by barbatus** [comment]
Install Meteor 1.3 typings by `typings install registry:env/meteor --ambient`
