### ISSUE TITLE
Cannot import meteor/mongo

### ISSUE THREAD

**Issue by Lavan** [barbatus/typescript#11]
I'm currently working on a small test application using angular 2 and meteor 1.3. In the spirit of doing things the recommended way I have only two files in the global directories that just does a few imports.

In one of my services (`/imports/client/services/service.ts`) I wish to access the meteor apis like this:

    import { Meteor } from 'meteor/meteor'
    import { Mongo } from 'meteor/mongo';
    import {Units} from '../../model/units.js';

I get the following errors:

    imports/client/services/recipe-service.ts (1, 24): Cannot find module 'meteor/meteor'.
    imports/client/services/recipe-service.ts (2, 21): Cannot find module 'meteor/mongo'.
    imports/client/services/recipe-service.ts (3, 21): Cannot find module '../../model/units.js'.

It looks like the compiler doesn't support the built-in `meteor/` prefix for resolving modules as well as not importing JavaScript files.

Not importing JavaScript would be ok as long as it's possible to import meteor packages.

**Comment by twastvedt** [comment]
I had the same problem. For now, I'm using [this definition file](https://gist.github.com/tomitrescak/8366ce98f1857e202ea8) instead of the automatic one. Found it [here](https://github.com/meteor/meteor/issues/6177).

**Comment by jacobdr** [comment]
Duplicate: https://github.com/barbatus/typescript/issues/6
