### ISSUE TITLE
Is there an example of how to use this in packages?

### ISSUE THREAD

**Issue by kokokenada** [barbatus/typescript#13]
I'm using an "all code in packages" approach and the generated .js files complain with "exports is not defined" during the build phase...

**Comment by jacobdr** [comment]
Do you have a small reproduction you can share? Or, at the least, an example of your code.

**Comment by kokokenada** [comment]
Thanks for the reply. I created a sample repo here: https://github.com/kokokenada/tstest

I now realize that it because I am also trying to use angular as in:
```
meteor create tstest
cd tstest
meteor add barbatus:typescript
meteor create --package testpackage
meteor add testpackage     # Built OK here
meteor add angular
meteor remove ecmascript
meteor remove blaze-html-templates # Now get an error (different from my other repo)
```

**Comment by jacobdr** [comment]
I am not sure exactly what the source of the error is, but running `meteor add modules` eliminated the compilation issue

**Comment by barbatus** [comment]
@kokokenada you are removing ecmascript (why?) from your app that's why you are getting  "exports is not defined". ecmascript comes with `modules`, by removing it you remove `modules`.

**Comment by kokokenada** [comment]
I thought the angular package is supposed to add the equivalent of emcascript and the tutorial (http://www.angular-meteor.com/tutorials/socially/angular1/bootstrapping) removes it too.    Anyways, I can confirm that 'meteor add modules' address the issue.  Thanks for the help.

**Comment by barbatus** [comment]
@kokokenada You are removing `ecmascript` in the tutorial to add `pbastowski:angular-babel` instead (Meteor doesn't allow multiple processor for one extension). And `pbastowski:angular-babel` doesn't seem re-adding `modules` package.
