### ISSUE TITLE
console.log Cannot find name 'console'

### ISSUE THREAD

**Issue by dagatsoin** [barbatus/typescript#15]
I am new to typescript in Meteor and following [this guide](https://atmospherejs.com/barbatus/typescript) I have an error `console.log Cannot find name 'console'`. (console.log("something"))

```
imports/lib/classes/entity/Entity.ts (70, 5): Cannot find name 'console'.
imports/lib/classes/entity/Entity.ts (105, 5): Cannot find name 'console'.
imports/lib/classes/entity/Entity.ts (110, 5): Cannot find name 'console'.
imports/lib/logicLayer/actions/actions.ts (15, 33): Property 'assign' does not exist on type 'ObjectConstructor'.
imports/lib/logicLayer/actions/actions.ts (21, 33): Property 'assign' does not exist on type 'ObjectConstructor'.
imports/lib/logicLayer/actions/actions.ts (27, 33): Property 'assign' does not exist on type 'ObjectConstructor'.

...
```

- After some research console.log seems to be defined in the default lib.d.ts, so how to be sure if it is imported at compilation?
- Object.assign is defined in the `es6-shim.d.ts`. I tried to `typings install --ambient es6-shim` and the errors on `Object.assign` are now gone. Is it the good definition? 

I have installed the @jacobdr (Thx for your help in #6!) meteor definition and my tsconfig.json is:
```
{
  "include": [" typings/main.d.ts "],
}
```
Note that tsconfig.json was not present after package installation and I created it manually. I don't know if it is normal as the readme does not state to create one. Does this file guides the IDE compiler (I use webstorm) or the meteor compiler?

My main.d.ts is:
```
/// <reference path="browser/ambient/es6-shim/index.d.ts" />
/// <reference path="browser/ambient/meteor/index.d.ts" />
```
Would not be useful to add some commons definitions as an advisable step in the installation readme (since Meteor uses Ecmascript2015 by default)?

Thx for your help.

**Comment by jacobdr** [comment]
I think that your setup is probably at fault here. When you use the `include` syntax of the `tsconfig.json`, you need to list *all* of the files that you want the compiler to compile. 

In your case I think you would need to include, for example: 
```
include: ["imports/lib/classes/entity/Entity.ts", "imports/lib/classes/entity/Entity.ts" ...]
```

That verbosity is why I have come to prefer the `exclude` syntax. 

Additionally, if everything in your `.tsconfig` file is wired up correctly, your reference path statements should be unnecessary (and are discouraged for reasons of portability).

The best way to provide you help would be for you to create a reproduction in a repository, and share that link here. I'm happy to take a look.

**Comment by barbatus** [comment]
@dagatsoin `lib.d.ts` looks like it's more suitable for browsers, so `lib.core.d.ts` is a default library for the server in this package. For example, console definition in `lib.d.ts` has methods like `dirxml` which is not true for the NodeJS. If you want to use node definition install Node typings additionally, i.e., `typings install node --ambient`.
`tsconfig.json` is not needed for the package, unless you want to fix your IDE's typescript.
Yes, it makes sense to update README regarding most useful typings like `es6-shim` and node; i'll do that soon.

**Comment by dagatsoin** [comment]
@barbatus sorry for the late response.

I am not sure I got it all. I removed `tsconfig.json` and indeed it was not necessary. The program compiles the same.

I have also done `typings install node --ambient` in `/server` (I thought you were talking about the root server folder in the meteor folder) and the definition appeared in `/typings/browser/ambiant` and `/typings/main/ambient`

But I still get the same error about the console.

**Comment by barbatus** [comment]
@dagatsoin Please read this https://github.com/Urigo/angular2-meteor/issues/246#issuecomment-215517441

**Comment by dagatsoin** [comment]
it works! Thx @barbatus.

**Comment by pureZjr** [comment]
your tsconfig.json

{
   ...,
   "lib":["dom"],
   ...
}
