### ISSUE TITLE
getting a lot of module not found message in my console

### ISSUE THREAD

**Issue by mattiLeBlanc** [barbatus/typescript#18]
Hi,

We use typescript with Angular and Meteor  and I do my imports at the top and get a lot of compiler message about the modules:
```
server/methods/invoice.ts (1, 38): Cannot find module '/imports/collections/invoices'.
server/methods/invoice.ts (2, 38): Cannot find module '/imports/collections/activatedInvoices'.
server/methods/invoice.ts (3, 38): Cannot find module '/imports/server/lib/httpHelper'.
server/methods/invoice.ts (4, 38): Cannot find module '/server/lib/invoice.class'.
server/methods/invoice.ts (5, 38): Cannot find module 'url'.
server/methods/invoice.ts (6, 38): Cannot find module '/server/lib/salesforce.class'.
server/methods/invoice.ts (7, 38): Cannot find module '/server/lib/xero.class'.
server/methods/invoice.ts (14, 8): Property 'scopedMethods' does not exist on type 'typeof Meteor'.
server/methods/lead.ts (1, 36): Cannot find module '/imports/lib/enums/statusCode.enum'.
server/methods/lead.ts (2, 36): Cannot find module 'url'.
server/methods/lead.ts (3, 36): Cannot find module '/imports/server/lib/httpHelper'.
server/methods/lead.ts (4, 36): Cannot find module 'auth0'.
server/methods/lead.ts (5, 36): Cannot find module 'jsonwebtoken'.
...etc..
```

Any idea how to resolve that? Apparently the modules are found otherwise the app would crash, right?

**Comment by barbatus** [comment]
Use NodeJS paths for modules, i.e, `../../imports/collections/invoices`.
Also, TypeScript will always curse on modules like `server/lib/salesforce.class` etc,
use `require('server/lib/salesforce.class')` instead for such modules.
To use NPMs w/o warnings, you'll need to install (if any otherwise to create) typings for them.

**Comment by mattiLeBlanc** [comment]
yes, I have installed most typings. Some are not complete however but that is a matter of time I reckon.
Using require( 'server/lib....' ) is not es6, is it?
I thought we could use the import syntax now with meteor 1.3

**Comment by mattiLeBlanc** [comment]
I dont understand why we can't use the import on the serverside without getting all those error messages.
When I use require, I get a message that require name cannot be found :-/

So or I get 
`server/methods/xero.ts (1, 30): Cannot find module 'meteor/meteor'.`
when I use
`import { Meteor }       from 'meteor/meteor';`
or
`server/methods/xero.ts (2, 14): Cannot find name 'require'.`
when I use
`var Meteor = require('meteor').Meteor;`

I am a bit at a loss. By the way the code works with both ways. Just the compiled going crazy.
Is your advice NOT to use Typescript on the server?
