### ISSUE TITLE
Runtime, cannot find module error

### ISSUE THREAD

**Issue by jerradpatch** [barbatus/typescript#19]
new to everything, meteor, .ts, npm in general. So, I am trying to make a single export file for my component which is split across multiple directives/folders. So at the root folder of the directive, I put a index.d.ts that exports all the components sub-directives. This compiles but when I load the site, I get cant find module error in the console.

 'uncaught Error: Cannot find module '../directives/VideosDisplay'

add this to tsconfig in file glob -  "client/**/*.d.ts", 

here is the index.d.ts in the root of the directives
export {VideosDisplay} from "./VideosDislay/VideosDisplay";
export {VideosDisplayNav} from "./VideosDislayNav/VideosDisplayNav";

inside VideosDisplayNav I have VideosDisplayNav.ts (same for VideosDisplay)

the goal is to able do this in another folder trying to use the components
import { VideosDisplay, VideosDisplayNav} from '../directives/VideosDisplay';

**Comment by jerradpatch** [comment]
PS, I am using angular2 with meteor, followed the tutorials for angular 2 on angular-meteor.com

**Comment by barbatus** [comment]
It's not clear why do you need any `index.d.ts` in a project that's not NPM. TypeScript resolves everything directly from `.ts`-files. Definitions files are usually placed in NPMs to help TypeScript to recognize which ES6 modules those NPMs export.
Also, messages like `Cannot find module '../directives/VideosDisplay'` usually say that you don't have a module with this path. So please check that it exists.
