### ISSUE TITLE
Error when adding package in a new Meteor 1.3.4 app in windows 10

### ISSUE THREAD

**Issue by reggieboyYEAH** [barbatus/typescript#22]
Hi i'm trying to add this package in my meteor app and I am encountering some error

![image](https://cloud.githubusercontent.com/assets/7448059/16331093/6f99fe7e-3a20-11e6-9cb9-6fa519dfedab.png)

Btw i am running on meteor 1.3.4 on a windows 10 machine

Not sure if this is related to issues
https://github.com/meteor/meteor/issues/6960
https://github.com/meteor/meteor/issues/7267

or the package itself. 

Edit:

Additional screenshot
![image](https://cloud.githubusercontent.com/assets/7448059/16331298/d83fcb4c-3a21-11e6-8ab9-393fc25e5994.png)

**Comment by artcab** [comment]
I am having this issue too, it's stuck at downloading, but no error is shown.

**Comment by barbatus** [comment]
Is still there with 1.3.4.1?
