### ISSUE TITLE
Chrome does not display source map after upgraded to v0.4 and Meteor 1.4.0.1

### ISSUE THREAD

**Issue by dagatsoin** [barbatus/typescript#23]
I though it was a misstake of my own, but I saw on Gitter someone with the same problem with meteor + angular 2. 
I posted a question on SO : http://stackoverflow.com/questions/38796793/browser-does-not-display-typescript-source-map

**Comment by sdarnell** [comment]
I have the same issue, but I thought I'd add the following info that may help reproduce the issue.
Install Meteor 1.4 or 1.4.0.1 - I'm using OS X, and then create the angular2 boilerplate example:
```
$ meteor create --example angular2-boilerplate boiler
To create the angular2-boilerplate example, please run:
  git clone https://github.com/bsliran/angular2-meteor-base boiler                              
$ git clone https://github.com/bsliran/angular2-meteor-base boiler
(This cloned at commit hash 96a7c8dae27cbeafaeb6710fe164afbec969edd2 July 28 2016)

$ cat .meteor/release 
METEOR@1.4
$ cat .meteor/versions
angular2-compilers@0.6.0
...
babel-compiler@6.9.0
babel-runtime@0.1.10
barbatus:angular2-runtime@0.5.0
barbatus:css-compiler@0.3.0
barbatus:scss-compiler@3.8.1_1
barbatus:typescript@0.4.0
barbatus:typescript-compiler@0.7.0
barbatus:typescript-runtime@0.1.2
...
caching-compiler@1.0.6
caching-html-compiler@1.0.6
...
ecmascript@0.5.7
ecmascript-runtime@0.3.12
...
minifier-css@1.2.13
minifier-js@1.2.13
...
standard-minifier-css@1.1.8
standard-minifier-js@1.1.8
...
urigo:static-html-compiler@0.1.7

$ npm install
...
$ meteor
...
=> App running at: http://localhost:3000/
```
Then in Chrome (mine was 52.0.2743.116) go to sources tab in dev tools, and navigate to top/App/client (this is the bottom of the two App folders).
Clicking on the 'main.ts' or 'app.component.ts' results in an empty source panel even though it says at the bottom "(source mapped from app.js)".

The link address is 'meteor://💻app/client/main.ts'.

If I update to meteor 1.4.0.1 the same problem occurs.

The resulting source map seems a bit limited:
```
$ vi .meteor/local/build/programs/server/app/app.js.map
```
<img width="991" alt="screen shot 2016-08-10 at 18 12 50" src="https://cloud.githubusercontent.com/assets/3684334/17563220/40a62770-5f26-11e6-8233-f02e81f82ed5.png">

**Comment by barbatus** [comment]
Should be fixed in the last version.

**Comment by sdarnell** [comment]
Sorry, precisely which 'last version' are you referring to?
This package (barbatus:typescript) version 0.4.0 still has the issue (see version info from above).
Meteor 1.4 and 1.4.0.1 both exhibit the problem, and 1.4.1 hasn't been released yet (it is still rc0).

**Comment by sdarnell** [comment]
Yes, that works now. Thanks!

For others coming here it might be work noting that angular2-compilers has been updated to 0.6.1 and includes the necessary version dependency to get the new packages.
