### ISSUE TITLE
"No plugin known to handle file (...)" when compiling a metor package in packages/

### ISSUE THREAD

**Issue by realyze** [barbatus/typescript#25]
Meteor@1.3.4.1

I have a package under packages/cpl and here's what I'm getting when I run `meteor` (for every .ts file in the package):

```
error: No plugin known to handle file 'lib/logger.ts'. If you want this file to be a static asset, use addAssets instead of addFiles; eg, api.addAssets('lib/logger.ts', 'client').
```

I've added `barbatus:typescript` to the `app.use` array in the package's `package.js`.

**Comment by barbatus** [comment]
I tried a sample package, works fine. Make sure you add `barbatus:typescript` to the server.
