### ISSUE TITLE
Sourcemap in meteor cordova Android does not appear

### ISSUE THREAD

**Issue by dagatsoin** [barbatus/typescript#26]
Is there a particular setup to have access to source map in a meteor cordova app ?

**Comment by dagatsoin** [comment]
gentle ping @barbatus :)

**Comment by barbatus** [comment]
I wonder how do you decide there is no sourcemap? Is it because there is no original source code or it doesn't debug at all?

**Comment by dagatsoin** [comment]
When you inspect the web view with Chrome, all the code is in app.js (but is not minimified).
If there is an error in the console, it will point to apps.js line XXXX
But there is no original folders ressources with the TS files like you can have when you debug a regular web app.

**Comment by dagatsoin** [comment]
@barbatus can I help on this? If you tell me what the final output should like, I can investigate on it.

**Comment by barbatus** [comment]
I've tested Cordova debugging in Safari and had no problem.
Yes, there is no special folder with all original ts-sources like when debugging Web 
version, but when you place a breakpoint anywhere in app.js, associated ts-file pops up in the debugger tab.
![screen shot 2016-08-25 at 7 21 27 pm](https://cloud.githubusercontent.com/assets/2824096/17977434/63123d5a-6afa-11e6-8fe4-73f42ce9f959.png)

**Comment by dagatsoin** [comment]
What version of your plugin are you using?

**Comment by barbatus** [comment]
barbatus:typescript@0.4.1

**Comment by dagatsoin** [comment]
I still use 0.3.1 because of an issue preventing having the source on the browser platform (this time...).
I ma trying another shot.

**Comment by barbatus** [comment]
I thought that issue was fixed long time ago.

**Comment by dagatsoin** [comment]
I confirm I have acces to source under IOS/Safari but not under Android/Chrome.
I also test on a HelloWorld fresh app and I get the same issue on Android/Chrome.

**Comment by barbatus** [comment]
Well it's strange. I seem though don't have Android emulator installed, so takes some time.

**Comment by barbatus** [comment]
obsolete

**Comment by gauravdhiman** [comment]
@barbatus I am also facing this issue. Not able to debug TS files using Chrome WebView Debugging when attached to Android phone. In debugger, I can only see the transpiled JS code created by barbatus, I can not see TS code in debugger. Please refer attached screenshot. Any idea, how we can debug cordova app (written in TS) using Chrome WebView Debugging. I am using MeteorJS on Ubuntu with Chrome and Android device.
![remote-webview-debugging](https://user-images.githubusercontent.com/5612223/29253915-2ed322d4-803e-11e7-87f9-c6866ef60a69.png)
