### ISSUE TITLE
meteor test --driver-package practicalmeteor:mocha doesn't work with ES6

### ISSUE THREAD

**Issue by jakobrosenberg** [barbatus/typescript#28]
After adding your package to my project, I can no longer run tests.

Default parameters and spread operators now produce ``unexpected token`` errors.

Running ``meteor`` without testing works fine.

**Comment by barbatus** [comment]
As an example, I can successfully run tests for Angular2-Meteor https://github.com/Urigo/angular2-meteor/tree/master/tests using same commands, which means either you are doing something wrong or have different tests app configuration (if it's an app)
So I'll need a repo to reproduce the issue.

**Comment by jakobrosenberg** [comment]
Blunder on my part. Fixed by setting target to ``es5``.

**Comment by Raemon** [comment]
Hey Jakobrosenberg - what do you mean by "setting target?" (we're running into vaguely similar issues trying to get meteor test to handle es5 stuff).

**Comment by jakobrosenberg** [comment]
Hi Raemon. Sorry about the late reply. Did you figure this one out? :)

**Comment by Raemon** [comment]
For some reason we needed to do "meteor test-package" instead of "meteor
test"
ᐧ
