### ISSUE TITLE
Unable to import modules from `/imports`

### ISSUE THREAD

**Issue by fabiospampinato** [barbatus/typescript#30]
Since the support for the new import/export syntax has become a good practice to move all the modules into an `/imports` folder, so that they won't get bundled by Meteor if nobody explicitly imports them.

My project structure looks like this:

```
app
├── imports
│   ├── enumerators
│   │   └── enumerator.ts 
│   └── modules
│       └── module.ts 
└── tsconfig.json
```

My `tsconfig.json` looks like this:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "commonjs",
    "moduleResolution": "node"
  }
}
```

From inside `module.ts` I can do:
- `import E from '/imports/enumerators/enumerator'`, which is understood by Meteor but not by TypeScript
- `import E from 'imports/enumerators/enumerator` (notice the lack of the initial slash), which is understood by TypeScript but not by Meteor

I don't want to use `import E from '../enumerators/enumerator'` which is understood by both for maintenance purposes, if I move the file in question to another path updating the imports is trivial if they uses an absolute path.

How am I supposed to make it work?

**Comment by barbatus** [comment]
The path like `imports/enumerators/enumerator` is non-relative, whic means imports like thats are always looked up in the node_modules folder in the node resolution strategy. Here is more on that https://www.typescriptlang.org/docs/handbook/module-resolution.html

**Comment by barbatus** [comment]
Also imports like/imports/enumerators/enumerator is understood by Meteor and this package, i.e., TypeScript integrated with Meteor.

**Comment by barbatus** [comment]
Just checked that with `"baseUrl": "."` TypeScript is able to resolve `'imports/enumerators/enumerator` correctly. That's because there is some sort of deviations possible configured by `baseUrl` and `path`. Meteor can't be configured like that, it sticks to node strategy strictly. There is only one way to overcome that is to transform import paths according to `baseUrl` and `path` options in the emitted code, which I thing makes sense to support in this package but some day in the future. For now I advice to use paths like `/imports/enumerator/enumerator`

**Comment by fabiospampinato** [comment]
I don't know if it was a matter of moving the whole project to TS of merely a need to close and re-open a file in Atom after having changed its extension, but `import/**/*` now works.

Thanks for your help.

**Comment by fabiospampinato** [comment]
Updating my previous comment: using `import/**/*` doesn't actually compile. 

Using `/import/**/*`, as I stated in the first post is only recognized by Meteor.

--

I tried opening the demo app that you point to in the readme and it's not working even there. For instance, once you cloned it go to `client/components/app.module.ts` and on line 14 there's the following import statement:

```
import {TaskList} from '/client/components';
```

which gets underlined in red with the following error: "Cannot find module '/client/components'".

I tried with both VSC and Atom with the atom-typescript plugin.

I'm running Meteor 1.4.1 and TypeScript 2.0.3.

Do you replicate the issue?

Perhaps that path transformation feature should be implemented. I could try to make a PR in you'll merge it.

**Comment by barbatus** [comment]
@fabiospampinato Like I said above, paths like `/client/components` are recognized by _this package, i.e., TypeScript integrated with Meteor_. You IDE's TypeScript won't able to do that. So you can rely only on the terminal output in this case.
Paths that starts with `/` or `./` seem not recognized in the `paths` option as well.

**Comment by barbatus** [comment]
Ok, it was fixed, check out https://github.com/barbatus/typescript/releases

**Comment by fabiospampinato** [comment]
Cool, thank you!
