### ISSUE TITLE
"No plugin known to handle file" only when calling meteor with test option!

### ISSUE THREAD

**Issue by dasdeck** [barbatus/typescript#31]
Hi!
I'm a happy user of your typescript package, so thanks for that :)
However, there is a problem when I try to add tests to my TS bases package.

```javascript
Package.describe({
    name: 'dasdeck:restcollection',
    version: '0.0.1',
    summary: 'a rest service resambling a collection',
    git: '',
    documentation: 'README.md'
});

Package.onUse(function (api) {
    api.versionsFrom('1.3');
    api.use('ecmascript');
    api.use('barbatus:typescript');

    api.use('jparker:crypto-md5');
    api.use('aldeed:simple-schema');
    api.use('underscore');
    api.use('jquery');


    api.addFiles('RESTObject.ts');
    api.addFiles('RESTCollection.ts');
    api.addFiles('RESTSearch.ts');
    api.addFiles('Converter.ts');
    api.addFiles('SchemaExtension.ts');
    api.addFiles('CollectionExtender.ts');

    api.addFiles('export.js');

    api.mainModule('export.js');

});

Package.onTest(function (api) {

    api.use('dasdeck:restcollection');
    api.use('practicalmeteor:mocha');
    //api.mainModule('test.js');

});
```
output:

```
/usr/local/bin/meteor --port 3020 test-packages --driver-package practicalmeteor:mocha
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> A patch (Meteor 1.4.1.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Errors prevented startup:
   
   While building package dasdeck:restcollection:
   error: No plugin known to handle file 'RESTObject.ts'. If you want this file
....
```
I could imagine that this is not really related to your packages, though it is obviously related.
Any ideas on where to start with this?

Thanks!

**Comment by barbatus** [comment]
How about setting exact version, i.e., `api.use('barbatus:typescript@0.4.1')`.
Packages require setting exact versions of the dependencies (except core ones)

**Comment by dasdeck** [comment]
Yes! Thanks a lot! I always wondered why the dependencies did not install on their own :/
Do you think this should throw an error from meteor's side?

Anyways, thanks for helping me out :)

Cheers!

**Comment by barbatus** [comment]
As I know, before you wouldn't be able to publish if exact versions are not set.
Why It doesn't load a package locally w/o any sign now - don't know. I might be an issue; make sense to check out if a similar issue's been raised already or create new one to ask at least.
