### ISSUE TITLE
Exporting a function from a .tsx file: Cannot invoke an expression whose type lacks a call signature.

### ISSUE THREAD

**Issue by sbking** [barbatus/typescript#33]
I have the two files:

/imports/startup/client/index.ts:

``` typescript
import initRouter from './initRouter';

initRouter();
```

/imports/startup/client/initRouter.tsx:

``` typescript
import * as React from 'react';
import { render } from 'react-dom';
import { Router, Route, IndexRoute, browserHistory } from 'react-router';

export default (): void => {
  render((
    <Router history={ browserHistory }>
      ...
    </Router>
  ), document.getElementById('root'));
};

```

When I run this I get the error:

`imports/startup/client/index.ts (3, 1): Cannot invoke an expression whose type lacks a call signature.`

I can get rid of the error by changing the import statement in index.ts to one of either:

`import initRouter from './initRouter.tsx';`

or

`import initRouter from '/imports/startup/client/initRouter';`

Am I incorrect in assuming that the compiler should be able to use the relative import path without the explicit file extension?

**Comment by barbatus** [comment]
I don't have that message in either ways.
