### ISSUE TITLE
Cannot read    property 'kind' of undefined

### ISSUE THREAD

**Issue by MastroLindus** [barbatus/typescript#35]
I am in the process of converting a meteor app to typescript. Meteor keeps spitting up a huge amount of errors without really giving me any clue on what it is the root cause of the problem.

While processing files with barbatus:typescript (for target os.linux.x86_64):
   /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:18813:42: Cannot read
   property 'kind' of undefined
   at getTypeForVariableLikeDeclaration
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:18813:42)
   at getWidenedTypeForVariableLikeDeclaration
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:18950:24)
   at getTypeOfVariableOrParameterOrProperty
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:19012:28)
   at getTypeOfSymbol
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:19149:24)
   at checkClassLikeDeclaration
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:30464:30)
   at checkClassDeclaration
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:30446:13)
   at checkSourceElement
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:31499:28)
   at Object.forEach
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:973:30)
   at checkSourceFileWorker
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:31580:20)
   at checkSourceFile
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:31562:13)
   at getDiagnosticsWorker
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:31615:17)
   at getDiagnostics
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:31606:24)
   at Object.getEmitResolver
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:16422:13)
   at emitWorker
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:44193:69)
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:44158:66
   at runWithCancellationToken
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:44239:24)
   at Object.emit
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:44158:20)
   at Object.getEmitOutput
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:57304:38)
   at CompileService.CP.compile
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/compile-service.js:28:29)
   at compile (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:197:33)
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:213:14
   at Cache.CCp.get
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/cache.js:169:19)
   at TSBuild.BP.emit
   (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:210:29)
   at packages/barbatus:typescript-compiler/typescript-compiler.js:107:28
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
   at packages/barbatus:typescript-compiler/typescript-compiler.js:121:7
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
   at replenish (/home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
   at /home/stefano/.meteor/packages/barbatus_typescript/.0.4.1.10i2ys7++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16

**Comment by barbatus** [comment]
Please try one of the latest versions. If this issue persists, pls re-open.
