### ISSUE TITLE
update to typescript 2.1-rc

### ISSUE THREAD

**Issue by hlehmann** [barbatus/typescript#36]
It will help us using async/await with es5 target.

**Comment by barbatus** [comment]
https://github.com/barbatus/typescript/releases

**Comment by scharf** [comment]
I think there is some strange mess-up with the typescript version numbers. https://github.com/Microsoft/TypeScript/issues/12655

`v2.1.1` is probably not a real release...

**Comment by barbatus** [comment]
OK, didn't know. Let's see how it goes, I'll revert if it's not good.

**Comment by aluanhaddad** [comment]
It is a release candidate. It is quite stable and I've been using it in production for weeks.
