### ISSUE TITLE
Issue using browser globals in an typescript file under imports

### ISSUE THREAD

**Issue by RichiCoder1** [barbatus/typescript#41]
We're following the structure outlined by https://guide.meteor.com/structure.html which included placing client side components in `imports/client/xyz`. The issue is I'm getting typescript errors with typescript complaining that I can't access 'window' and 'sessionStorage'. Is there a way to fix this?

**Comment by barbatus** [comment]
It's missing. Will add in the next version soon.

**Comment by barbatus** [comment]
I hurried up a bit with the above comment. I tested recently and figured that files from paths like `imports/client` are bypassed server compilation by Meteor itself (which is logical). If you run your project with `TYPESCRIPT_LOG=1` you will see that first set (for the client) of `compile files` include `imports/client` files while second set (for the server) doesn't contain it.

**Comment by barbatus** [comment]
Closing. If you still have it, please, re-open and update the status.
