### ISSUE TITLE
Cannot find module 'meteor/meteor'

### ISSUE THREAD

**Issue by RJZS** [barbatus/typescript#42]
I have added Typescript to my Meteor + React project, but am receiving the compile error Cannot find module 'meteor/meteor' in my main.tsx files in the /client and /server folders. I followed the install instructions as detailed in the readme.

```
import React from 'react';
import { Meteor } from 'meteor/meteor';
import { render } from 'react-dom';

import App from '../imports/App';

Meteor.startup(() => {
	render(<App />, document.getElementById('render-target'));
});
```

**Comment by barbatus** [comment]
Install `meteor-typings` NPM (npm i meteor-typings --save) and add it to the `tsconfig.json` as `"types": ["meteor-typings"]`

**Comment by RJZS** [comment]
Thanks for your reply. I installed meteor-typings and added the line to my /client and /server tsconfig.json files, but unfortunately the problem remains.
