### ISSUE TITLE
lib.d.ts declarations are not processed

### ISSUE THREAD

**Issue by MastroLindus** [barbatus/typescript#44]
I recently upgraded my environment (meteor@1.4.2, typescript@2.2, and reinstalled barbatus:typescript) and now during my compilation step I get a lot of errors for undefined symbols like "alert" "setTimeout" "clearTimeout" etc.

My IDE correctly points me to the lib.d.ts file containing those definitions, so it doesn't give me any error sign, but the command line compilation from meteor gives me many of these errors.

My previous setup with a older version of the packages used to work fine.

**Comment by MastroLindus** [comment]
I added 
"lib": ["dom","es5"] 
to my tsconfig.json, and it seems that now the compiler is happy and the app works fine, not sure thought if it is the best solution

**Comment by barbatus** [comment]
"lib": ["dom","es5"] is set by default, so if you remove it from the config it should work as well, but 
people usually keep it for clarity.
