### ISSUE TITLE
Intermittent compilation errors

### ISSUE THREAD

**Issue by rwdietrich** [barbatus/typescript#47]
I've been developing an application recently, and have run into a strange error that has me stopped cold. Here are the steps to make the errors appear (update: occurs on Linux as well as Windows 10):

Clone the git repository for this project and cd.
Run meteor npm install.
Run meteor and the application works fine.
Stop meteor (two control-C's) and then start again (meteor). The errors below appear and the app doesn't run.
If you run meteor reset followed by meteor, the application runs again once.
The problem occurs with versions 1.4.2.7 and 1.4.3.2 of meteor, as well as 0.6.3 and 0.6.5_1 of barbatus/typescript.

I would greatly appreciate suggestions on how to track this down (or a fix). Thanks.

From Linux (abbreviated):
```
=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with barbatus:typescript (for target web.browser):

   /home/bobd/.meteor/packages/barbatus_typescript/.0.6.5_1.11kuj6j++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/utils.js:91:12:
   false == true
   at exports.assertProps
   (/home/bobd/.meteor/packages/barbatus_typescript/.0.6.5_1.11kuj6j++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/utils.js:91:12)
   at createCSResult
[...]
```

**Comment by barbatus** [comment]
are you still experiencing this with new versions of Meteor and this package?

**Comment by weini01** [comment]
I´ve the same Problem with Meteor 1.5.1 and 0.6.7 barbatus:typescript only a meteor reset works for me.  I would be very grateful for any help. Thanks.

**Comment by dusted** [comment]
@barbatus i'm having the same problem with my angular-meteor project Meteor 1.3.5.1, 0.3.3 barbatus:typescript

**Comment by dusted** [comment]
@barbatus  i managed to solve this by running 
```
 meteor update --all-packages
```

**Comment by barbatus** [comment]
@dusted awesome. though if you bump into it again pls run `meteor TYPESCRIPT_LOG=2` and post it here or in a new issue.

**Comment by weini01** [comment]
I've figured out why it did not work: I had a file I didn´t need anymore so I commented out the whole code in the file. 
Although I imported it nowhere I got this error. After deleting this file it works!!

**Comment by rwdietrich** [comment]
Sorry, was dealing with other matters. The problem continues for me. Here is a cut down example run:

**Comment by barbatus** [comment]
There is a new version already 0.6.8.
How often this particular thing happens to you?
Does it go away if you run `meteor reset`?
@rwdietrich Can pls run `TYPESCRIPT_LOG=2 meteor` and send a log to me?

**Comment by rwdietrich** [comment]
@barbatus Files sent, and thanks. To answer your questions: 1) I will try 0.6.8, but this issue has occurred with various versions since March.  2) It is very consistent - happens every time unless `meteor reset` is run first. This includes running `meteor lint`.  3) Yes, the run does not fail after a meteor reset.

**Comment by rwdietrich** [comment]
Tried 0.6.9. Still fails if a `meteor reset` is not done before running meteor.

**Comment by barbatus** [comment]
@rwdietrich does it fail when it's running and you make a change? Or do you need to stop it and rerun to reproduce?

**Comment by rwdietrich** [comment]
@barbatus Yes to the second question. Changing code on the fly works fine.

**Comment by barbatus** [comment]
@rwdietrich I suspect that cache contents are not being saved properly. Can you pls go to `.meteor/local/.typescript-cache` and check that any random cache file has a content, and paste it here? What OS are you using?

**Comment by rwdietrich** [comment]
After a run (successful or not), there are 620 files in the cache, ranging in size from 42 bytes to 119190. I have emailed the largest file. This fails both on Windows 10 and Linux (Fedora 25).

**Comment by barbatus** [comment]
@rwdietrich i added a bit more logs. please update to 0.6.10 and run `TYPESCRIPT_LOG=2 meteor` when it fails, then please send the log to me.

**Comment by rwdietrich** [comment]
Thanks, I've sent the file.

**Comment by rwdietrich** [comment]
It's fixed. Thanks, @barbatus !
