### ISSUE TITLE
Non-relative module resolution by path mapping (tsconfig.json "baseUrl" + "paths") support?

### ISSUE THREAD

**Issue by KeithGillette** [barbatus/typescript#48]
I see from the README.md that this TypeScript compiler has support for [module resolution via path mapping with "limitations"](https://github.com/barbatus/typescript/blob/e991ce6ebe9e6af7f323902afca2a7d605211728/README.md#path-mappings).

I have an Angular-Meteor project using:

- METEOR@1.4.3.2
- barbatus:typescript@0.6.5_1
- barbatus:typescript-compiler@0.9.5
- barbatus:typescript-runtime@1.0.0

When I attempt to use the `baseUrl` and `paths` properties in `tsconfig.json` to resolve non-relative modules in a `node_modules` directory outside of the Meteor project directory, the compiler is unable to find the matching paths, which it prefixes with a `/` in the output. Is this one of the current limitations?

**Comment by barbatus** [comment]
Yes it's not possible because Meteor can't bundle files outside of the project directory.

**Comment by KeithGillette** [comment]
Thanks for the clarification, @barbatus.
