### ISSUE TITLE
'Cannot find module' error when attempting to resolve relative modules outside of Meteor root directory

### ISSUE THREAD

**Issue by KeithGillette** [barbatus/typescript#49]
Perhaps related to the same limitation leading to issue #48, if I attempt to import a module from a directory outside of the Meteor root directory, I get an error of the form:

`Cannot find module '../../../path-to-module/module-name'.`

Project dependencies:
- METEOR@1.4.3.2
- barbatus:typescript@0.6.5_1
- barbatus:typescript-compiler@0.9.5
- barbatus:typescript-runtime@1.0.0

**Comment by ClarenceL** [comment]
I have similar issues with a local package, relative paths are inconsistent

**Comment by barbatus** [comment]
meteor can't import modules from outside app directory
