### ISSUE TITLE
Why do types need to be manually specified?

### ISSUE THREAD

**Issue by abecks** [barbatus/typescript#50]
The readme states: 

> To install Meteor declaration files, install meteor-typings NPM and change tsconfig.json as follows:
``
{
  "compilerOptions": {
    "types": ["meteor-typings"]
  }
}
``

I've noticed that you need to manually add each type that you install (via npm @types) to this list. The TypeScript documentation says that the compiler should check for these types on its own. 

Can anyone shed some more light on this?

**Comment by barbatus** [comment]
Typescript looks for typings in @types for corresponding NPM packages. Meteor is not NPM package that's why you need to add it manually.

**Comment by abecks** [comment]
I have to manually specify all types, including npm packages

**Comment by barbatus** [comment]
Lets say I use lodash and have `@types/lodash` installed then I don't need to add any types or anything else to the config. When I do `import { trim } from 'lodash'` Typescript checks this import in `@types/lodash` typings.
