### ISSUE TITLE
Upgrade to TypeScript 2.3

### ISSUE THREAD

**Issue by scharf** [barbatus/typescript#51]
[TypeScript 2.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html) is out.

I wish there was a way to upgrade typescript externally....

**Comment by scharf** [comment]
I wonder if there is a way to help updating to new versions of typescript? Typescript is now at version [2.3.2](https://github.com/Microsoft/TypeScript/releases/tag/v2.3.2)

**Comment by barbatus** [comment]
Upgraded to 2.3.2
