### ISSUE TITLE
README.md saying "it's possible to use ES6 on the server" is not entirely correct

### ISSUE THREAD

**Issue by untsamphan** [barbatus/typescript#53]
I've tried as the document suggested and the server couldn't run. It seems Node.js v4 (mine is v4.8.2) doesn't support destructuring.

See https://stackoverflow.com/questions/40702220/syntaxerror-when-importing-es6-npm-module-in-meteor

**Comment by barbatus** [comment]
yes Node v4 has limited support of ES6 features. Soon though Node will be upgraded to v6 in Meteor 1.6 which has 95% support of ES6.
