### ISSUE TITLE
Include private package

### ISSUE THREAD

**Issue by staeke** [barbatus/typescript#55]
It seems to me there is no proper way to include one's own packages. First, let's assume the following directory structure:

```
client/
    client.ts
packages/
    my-package/
        package.js
        pkg-server.ts
        pkg-client.ts
server/
    tsconfig.json
    server.ts
tsconfig.json
```

The `package.js` is written as you'd think and the package is added to `packages`. Now, the meteor way of including this package is by writing

```typescript
// From server.ts
import {serverFn} from 'meteor/my-package'

// From client.ts
import {clientFn} from 'meteor/my-package'
```

But...this yields a typescript error. AND, doesn't play well with editors which don't want to generate such imports. 

Enter typescript paths! So I assumed I'd create `tsconfig.json` path mappings. Like:

```js
// tsconfig.json
...
"target": "es5",
"module": "commonjs",
"baseUrl": ".",
"paths": {
   "meteor/my-package": ["packages/my-package/pkg-client"]
}
...

// server/tsconfig.json
...
"target": "es5",
"module": "commonjs",
"baseUrl": ".",
"paths": {
   "meteor/my-package": ["../packages/my-package/pkg-server"]
}
...
```

This works well with tools (WebStorm) and Typescript. But...unfortunately not with meteor. So, it seems to me either it works with meteor OR WebStorm/Typescript. Any ideas? Otherwise, consider this a feature request for fixing it.

**Comment by barbatus** [comment]
well, I have similar path mapping tests, and they pass. I also tested briefly if it works in the real example, https://github.com/barbatus/test-app

**Comment by barbatus** [comment]
Seems to be not actual. Reopen if you still have questions
