### ISSUE TITLE
How to find out which version the current typescript package is based on?

### ISSUE THREAD

**Issue by scharf** [barbatus/typescript#57]
The documentation says:

> TypeScript@2.4.0

Is there a way to figure out what exact version is used in this package? Is it really `2.4.1` or `2.4.2`?

**Comment by barbatus** [comment]
@scharf it should be as here https://github.com/barbatus/meteor-typescript/blob/master/package.json#L36.
The actual version now is 2.4.2.

**Comment by scharf** [comment]
Thanks!
