### ISSUE TITLE
Long build times -- Meteor 1.5

### ISSUE THREAD

**Issue by tmpg** [barbatus/typescript#62]
Hey,

My project was getting big and I wanted to refactor with typescript. I am loving it so far but the rebuilds are very long. Is there any suggestion on how to make it shorter or options I can switch or tune?

Let me know.

Thanks,
Tim

**Comment by barbatus** [comment]
Pls run TYPESCRIPT_LOG=3 meteor and post logs here

**Comment by barbatus** [comment]
Pls reopen if the problem persists
