### ISSUE TITLE
Clarification on the validity of symlink hackery for /imports

### ISSUE THREAD

**Issue by convexset** [barbatus/typescript#65]
I'm new to TS+Meteor, and have been trying to get them to work together.

I'm using VS Code (supposedly gold standard for TS) and have been trying to get Intellisense to work with imports. Imports like:
```
import styledComponentWithProps from '/imports/view/styled-component-with-props';
```
are not recognized by VS Code, and I lose Intellisense support.

So i've tried to symlink `/imports` to `/node_modules/imports` and things seem to work out:
 - Intellisense resolves my type information
 - server side code is hidden from the client (big surprise there)

I'd like to clarify that the above is all by design or inevitable consequence of design decisions. Also, whether anything strange is going on. (I find the symlink step to be an ugly hack but something I can live with to get my type information.)

I tried this because I have not been able to get `baseUrl` and `paths` to work see my `/tsconfig.json`...
```
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "moduleResolution": "node",
    "alwaysStrict": true,
    "sourceMap": true,
    "jsx": "react",
    "allowJs": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "lib": [],
  "include": [
    "client/**/*",
    "server/**/*",
    "imports/**/*"
  ],
  "exclude": [
    ".meteor",
    "node_modules"
  ],
  "typeRoots": [
    "typings"
  ],
  "baseUrl": "./",
  "paths": {
    "@client/*": ["imports/client/*"],
    "@server/*": ["imports/server/*"],
    "@data/*": ["imports/data/*"],
    "@view/*": ["imports/view/*"]
  }
}
```

So:
 - Is my symlink trick something that makes sense from the build stand point? Any other side effects?
 - Any prospect of getting remapping through the `baseUrl` and `paths` to work... I've looked at other issues and it looks like a lost cause for now. (Would mapping also respect the server/client separation of code?)
 - Does the package exclude server code from client builds and client code from server builds regardless of symbolic links?

**Comment by barbatus** [comment]
Seems obsolete. Please read this section https://github.com/barbatus/typescript#path-mappings, hopefully, it'll resolve your issue
