### ISSUE TITLE
absolute import path not working

### ISSUE THREAD

**Issue by dtruel** [barbatus/typescript#69]
Hello, and thanks for all your hard work on this package!

I'm trying to import this file located at /imports/people/Person.ts like this:
```
import Person from "imports/models/Person";
```
I'm doing this because the readme says that this is how you import absolute files.  This makes my IDE happy. However, when I run the program is says "Error cannot find module".  Adding a slash to the beginning of it fixes the problem but makes my IDE mad.  I read this issue https://github.com/barbatus/typescript/issues/30 and it seemed like this has been fixed, but for whatever reason it is not working.  I am using these packages:

barbatus:typescript@0.6.12
barbatus:typescript-compiler@0.9.12
barbatus:typescript-runtime@1.0.2

**Comment by jschmold** [comment]
Hey, I found a better way to accomplish what you are trying to do, and it works beautifully. In your tsconfig.json, there's an option called `baseUrl` and another called `paths`. Anything that you put in there you can consider to be an alias.

My package structure:
```
moduleName -- shared files
moduleName/client -- Client only files
moduleName/server -- Server only files
```

I wanted to reference each module by name, using the `@` symbol, with `shared` being implied if no specifier is given.

server: 
`import { svToken } from "@tokens/server"`
shared: 
`import { token } from "@tokens/shared"` or `import { token } from "@tokens"`
client: 
`import { clToken } from "@tokens/client"`

```json
{
    "baseUrl": ".",
    "paths": {
      "@*/shared": ["imports/api/*"],
      "@*/client": ["imports/api/*/client"],
      "@*/server": ["imports/api/*/server"],
      "@*": ["imports/api/*"]
    }
}
```

**Comment by dtruel** [comment]
Hey jschmold, thanks for the input. I don't understand what the @ is about.  What does it do?

**Comment by jschmold** [comment]
@dtruel 
The `@` really doesn't have much meaning other than convention. If you look at virtually [any](https://angular.io/api/animations/browser/AnimationDriver) Angular doc, the npm packages are all prefixed with an `@` symbol, indicating they're a package. They're of no significance, and you can get away with real words of your choosing. I just chose to treat everything under my `api/` directory as a package in and of itself for cleanliness sake.

**Comment by dtruel** [comment]
THanks @jschmold 

I figured out the problem. I'm using vue single file components and it turns out that typescript files therein are compiled using a different plugin which doesn't support this: https://github.com/nathantreid/meteor-vue-typescript
