### ISSUE TITLE
Not detecting .ts files

### ISSUE THREAD

**Issue by ndarilek** [barbatus/typescript#7]
Just spent the past couple hours trying to Migrate a Meteor 1.3 app partially to TypeScript. I installed this package, converted my formerly .coffee files to JS, gave the resulting JS a .ts extension and started gradually adding types. On app launch I received no errors, which was suspicious. When I modified my .ts files or created new ones, I didn't see them detected and the server or client restarted.

As an experiment, I created a new Meteor 1.3 app, added this package and spun it up. I then touched server/index.ts, but I never saw the server restart. By way of contrast, `touch server/index.js` causes a restart even though the files are both empty.

Am I missing something? Of possible note is that I haven't imported the Meteor types because I understand they haven't been updated to Meteor 1.3 yet. I also haven't really delved into typings at all. I'm currently just using TS to replace the _check_ package, and to give my functions type annotations. Not sure if that might be the cause. I do plan to investigate the typings ecosystem eventually but thought I'd do so incrementally.

Thanks.

**Comment by barbatus** [comment]
I don't think it has any connection to the typings. You'd rather get a lot of warnings if you don't have them at all. It seems to be really strange that TypeScript files are not recognized. I have no ideas what it might be, so I'll need a repo with your issue or (exact steps) to investigate.

**Comment by ndarilek** [comment]
With Meteor 1.3 installed:

```
meteor create test
cd test
meteor add barbatus:typescript
meteor
```

 From another terminal:

```
touch server/index.ts
```

The server does not reload.

```
touch server/index.js
```

The server reloads.

**Comment by barbatus** [comment]
yes, there is an issue with versions. It adds some old version 1.5 by default while current one is 0.2.0. I am investigating why now. But if you do `meteor add barbatus:typescript@0.2.0`, it should work.

**Comment by barbatus** [comment]
Ok, fixes. `meteor add barbatus:typescript` should install proper version now.
