### ISSUE TITLE
When does it support TypeScript 3?

### ISSUE THREAD

**Issue by jeehyukwon** [barbatus/typescript#76]
I wanna use `styled-components` with Props ([How do I provide props to styled elements in Typescript?](https://github.com/styled-components/styled-components/issues/630)) in my meteor-react project.

But, TypeScript supports **Generic type arguments in generic tagged templates** since 2.9.2. [TypeScript 2.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html)

So, is there any plan for supporting TypeScript 3?

**Comment by yorrd** [comment]
try our fork, it is running on ts 3.2.2

https://atmospherejs.com/adornis/typescript
