### ISSUE TITLE
Module resolution failure

### ISSUE THREAD

**Issue by ndarilek** [barbatus/typescript#9]
Steps to reproduce:

1. Clone [this repository](https://github.com/ndarilek/meteor-typescript-module-resolution-failure/).
2. Run `npm install`.
3. Run `meteor`.

Result: An error that the uuid module can't be found, plus a long stacktrace which appears to include the `uuid()` function source.
Expected result: A message `Starting up` followed by a UUID.

Note that if you move main.ts to main.js, everything works. There is a TS declaration for the uuid module, but my expectation is that this would just work and warn me about it rather than fail out-right. I don't know if the error about missing the module refers to the type definitions for the module or the module itself--based on the tutorial you linked I'm guessing the former--but it seems like it should work nonetheless.

Thanks.

**Comment by barbatus** [comment]
README page of this package clearly says:
````
var uuid = require('uuid');
 
// Generate a v1 (time-based) id 
uuid.v1();
....
````
So the correct way to work with it will be  `import {v1} from "uuid"`.
Also if you look at the error carefully you will see a message `has no method 'default'`. This is also related to the reason why `import uuid from "uuid"` doesn't work if converted to ES5.

**Comment by ndarilek** [comment]
That is certainly one way to work with the package, sure, but my way 
works too. Verify by `mv server/main.ts server/main.js` and watch it 
work. Also verified via the node command line. This is also how I'm 
using this uuid module in my production app so I definitely don't need 
help using it correctly. :)

Thanks for spotting the error re: default. I'm blind, and listening to 
all of that error text with my screen reader would have been painful. 
Usually I locate the `throw` line and find the actual cause a line or 
two below. This particular error seems oddly formed.

So what would be the way to work around this? I tried this tsconfig.json:

```
{
   "compilerOptions": {
     "module": "es2015",
     "target": "es6",
     "jsx": "react",
     "moduleResolution": "node",
     "experimentalDecorators": true,
     "emitDecoratorMetadata": true,
     "sourceMap": true,
     "noEmitHelpers": true
   }
}
```

And now I get:

```
server/main.ts (1, 18): Cannot find module 'uuid'.
server/main.ts (3, 1): Cannot find name 'Meteor'.
[34mW20160330-18:30:55.379(-5)? (STDERR) [39m[35m[39m
[34mW20160330-18:30:55.379(-5)? (STDERR) 
[39m[35m/home/nolan/Projects/Perceptron/meteor-typescript/.meteor/local/build/programs/server/app/app.js:9[39m
[34mW20160330-18:30:55.380(-5)? (STDERR) [39m[35mimport uuid from 
"uuid";                                             //[39m
[34mW20160330-18:30:55.380(-5)? (STDERR) [39m[35m^^^^^^[39m
[34mW20160330-18:30:55.383(-5)? (STDERR) [39m[35mSyntaxError: 
Unexpected reserved word[39m
[34mW20160330-18:30:55.383(-5)? (STDERR) [39m[35m    at 
/home/nolan/Projects/Perceptron/meteor-typescript/.meteor/local/build/programs/server/boot.js:278:30[39m
[34mW20160330-18:30:55.383(-5)? (STDERR) [39m[35m    at 
Array.forEach (native)[39m
[34mW20160330-18:30:55.383(-5)? (STDERR) [39m[35m    at 
Function._.each._.forEach 
(/home/nolan/.meteor/packages/meteor-tool/.1.3.0_3.1l3dtaj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20160330-18:30:55.383(-5)? (STDERR) [39m[35m    at 
/home/nolan/Projects/Perceptron/meteor-typescript/.meteor/local/build/programs/server/boot.js:133:5[39m
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Thanks, I appreciate all your help. Trying to read docs and familiarize 
myself with TS but I don't quite get where it ends and Meteor's own 
build tool begins.

**Comment by barbatus** [comment]
Ok, I'll try to elaborate.

The reason why `import uuid from "uuid"` works well with `ecmascript` is that `ecmascript` doesn't compile ES6 for the server side at all, which means same expression `import uuid from "uuid"` is executed by NodeJS ultimately.

At the same time, `typescript` package currently can compile server side code to ES5 only, and that expression `import uuid from "uuid"` if compiled to ES5 doesn't work for the "uuid" package.

Thanks for the raising this issue though. Compilation to ES6 for the server side by default (if installed version of NodeJS allows) might become one of the next features of this package.

**Comment by ndarilek** [comment]
Ah, got it, that was the missing piece for me. I couldn't figure out 
which packages can and can't compile to and from which ecmascript 
versions. :)

So, reading this, I can't use import at all in TypeScript right now? Or 
there's something specific to the uuid package that doesn't quite work 
when imported in TS yet? I may be conflating a few different 
misunderstandings here, since I'm also told the module can't be found 
but that may be due to the declaration not being installed.

Thanks for your patience.

**Comment by barbatus** [comment]
You still can use `import {v1} from "uuid"`. I just verified that it works well.
Every other messages (like module can't be found) are likely related to the missing declaration files (typings). Just download this declaration file https://raw.githubusercontent.com/DefinitelyTyped/tsd/master/typings/uuid/uuid.d.ts and put it into the typings folder. It should solve the issue.  (I was unable to install it directly using `typings install uuid --ambient` as it should be, it looks like there is another one library with the same name)

**Comment by ndarilek** [comment]
Got it. Thanks so much. What about the cases where I get "module not 
found" for my own modules? I don't need declarations for those too, do 
I? I thought annotating my functions with types would be sufficient.

**Comment by barbatus** [comment]
Yes, your own modules don't require any declaration files, they are declaration files by themselves.
But I don't get yet why do you have this issue. I just verified one more time and it works well for me.
For example, I put a test file in `server/test/foo.ts` with an random exported variable, and then imported it in `server/main.ts`. No errors in the terminal.

**Comment by ndarilek** [comment]
Yeah, oddly enough I can't duplicate this either in the test repo, but 
literally every single import in my production app reports:

```
server/tasks.ts (1, 21): Cannot find module 'meteor/alanning:roles'.
server/tasks.ts (2, 22): Cannot find module 'meteor/meteor'.
server/tasks.ts (3, 20): Cannot find module 'moment'.
server/tasks.ts (4, 19): Cannot find module 'node-fetch'.
server/tasks.ts (5, 18): Cannot find module 'uuid'.
server/tasks.ts (7, 40): Cannot find module '/lib/models'.
```

Which admittedly is a bad error if it's just a matter of not being able 
to find declarations, but that's probably outside of your control. And 
/lib/models/index.js is my own module, so I don't know why it would 
throw the same error used to report missing declarations. I tried 
renaming it to index.ts but it still reports as missing, only then 
/lib/models/index.ts starts reporting all of its _own_ modules as 
missing. :)

It's odd to me that not being able to find a module isn't treated as an 
actual error. I.e. my app claims to be running despite screens upon 
screens of errors like these.

But now I've run `git mv` on all the files in /lib/models to give them 
.ts extensions, and this time the app crashes. Here is the error log in 
case it helps:

```
[34mW20160330-21:07:03.980(-5)? (STDERR) [39m[35m[39m
[34mW20160330-21:07:03.981(-5)? (STDERR) 
[39m[35m/home/nolan/.meteor/packages/meteor-tool/.1.3.0_3.1l3dtaj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267[39m
[34mW20160330-21:07:03.981(-5)? (STDERR) [39m[35m         throw(ex);[39m
[34mW20160330-21:07:03.981(-5)? (STDERR) [39m[35m               ^[39m
[34mW20160330-21:07:04.082(-5)? (STDERR) [39m[35mError: Cannot find 
module './models'[39m
[34mW20160330-21:07:04.082(-5)? (STDERR) [39m[35m    at require 
(packages/modules-runtime.js:95:19)[39m
[34mW20160330-21:07:04.083(-5)? (STDERR) [39m[35m    at 
meteorInstall.lib.presence.ts (lib/presence.ts:1:1)[39m
[34mW20160330-21:07:04.083(-5)? (STDERR) [39m[35m    at 
fileEvaluate (packages/modules-runtime.js:158:9)[39m
[34mW20160330-21:07:04.083(-5)? (STDERR) [39m[35m    at require 
(packages/modules-runtime.js:92:16)[39m
[34mW20160330-21:07:04.084(-5)? (STDERR) [39m[35m    at 
server/tasks.ts:473:3[39m
[34mW20160330-21:07:04.084(-5)? (STDERR) [39m[35m    at 
/home/nolan/Projects/Perceptron/App/.meteor/local/build/programs/server/boot.js:283:10[39m
[34mW20160330-21:07:04.084(-5)? (STDERR) [39m[35m    at 
Array.forEach (native)[39m
[34mW20160330-21:07:04.084(-5)? (STDERR) [39m[35m    at 
Function._.each._.forEach 
(/home/nolan/.meteor/packages/meteor-tool/.1.3.0_3.1l3dtaj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)[39m
[34mW20160330-21:07:04.085(-5)? (STDERR) [39m[35m    at 
/home/nolan/Projects/Perceptron/App/.meteor/local/build/programs/server/boot.js:133:5[39m
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

tasks.ts:473 is:

```
})
```

I.e. the last line in the file. lib/presence.ts:1:

```
import {User} from "./models"
```

My app is not open source. I may be able to send it to you privately if 
you're interested, otherwise I can just revert to how it was before. 
This isn't critical, I'd just hoped to start gradually introducing types 
and thought this'd be a simple rename of files to .ts, fix errors, save, 
repeat...

**Comment by barbatus** [comment]
Top five "Cannot find module" happens due to absence of the associated typings:
```
server/tasks.ts (1, 21): Cannot find module 'meteor/alanning:roles'.
server/tasks.ts (2, 22): Cannot find module 'meteor/meteor'.
server/tasks.ts (3, 20): Cannot find module 'moment'.
server/tasks.ts (4, 19): Cannot find module 'node-fetch'.
server/tasks.ts (5, 18): Cannot find module 'uuid'.
```

The last one `Cannot find module ./lib/models` is shown because you don't have any file with `modules` name. I guess, you are assuming here that everything should be imported from index file, i.e, `./lib/models/index.ts`, but TypeScript doesn't  work with `index` files so far. You'll need to import objects differently from this file, i.e., `import * from '/lib/models/index'`.

**Comment by ndarilek** [comment]
Ah, thanks for mentioning the lack of index support. That does indeed 
seem to resolve part of the problem

So I tweaked the above repository, added a server/test/index.ts that 
imports server/test/bar.ts. I added an import of server/test/index in 
main and re-exported a variable from bar in server/test/index. The 
variable prints, but now I get the "cannot find module ./bar" error in 
server/test/index even though everything works.

bar.ts is a TypeScript file, so I don't know why it'd need declarations.

Thanks.

**Comment by ndarilek** [comment]
Also, something else I just thought of. In my production app I get:

```
Cannot find module 'moment'.
```

I definitely have the moment typings module installed:

```
typings install --save --ambient moment
```

I just wiped out my typings directory and reran `typings install` to be 
sure. I think that's another point of confusion. The compiler is 
supposed to include all *.ts files, and I've used typings to install 
various modules' definitions, but they still claim to be missing even 
though I'm told that's what this error means. I've confirmed the 
declaration file for moment is on my filesystem.

Thanks for keeping up with my stream of updates. :) I've switched back 
to JS for the time being. Happy to keep debugging this if you have the 
time, but it isn't critical for me. Was hoping a TS migration would be a 
bit more frictionless, and that I could gradually incorporate type 
definitions until the full API was covered.

**Comment by barbatus** [comment]
You'll rather need moment typings for Node, i.e., `typings install moment-node --save --ambient`.
I just verified that the code below works well with no errors in the terminal:
```
import * as moment from 'moment';

console.log(moment.now());
```
Also I checked quickly your sample with `./test/index` and `./test/bar`. No errors were found there as well. Hope you don't specify `server` in paths.

This package is actually one of the prerequisite for the [`angular2-meteor`](https://github.com/Urigo/Meteor-Angular2) package, which is quite popular now.
While I see issues related to wrong imports from time to time; they come mostly from beginners. Majority people don't have blocking (at least) issues using it.

**Comment by ndarilek** [comment]
Got it, thanks for the moment-node tip.

So when you start my sample app, you don't see this startup sequence?:

```
```[[[[[ ~/Projects/Perceptron/meteor-typescript ]]]]]

=> Started proxy.
=> Started MongoDB.
server/test/index.ts (1, 17): Cannot find module './bar'.
server/main.ts (1, 18): Cannot find module 'uuid'.
server/main.ts (5, 1): Cannot find name 'Meteor'.
=> Started your app.

=> App running at: http://localhost:3000/
[34mI20160331-09:02:32.920(-5)? [39mStarting up 
36cebd60-f749-11e5-83ff-4dded6b7eb6b
[34mI20160331-09:02:32.922(-5)? [39mNonsense value { foo: 5 }
```

I.e. particular emphasis on:

```
server/test/index.ts (1, 17): Cannot find module './bar'.
```

And even though it claims the module can't be found, it happily displays 
the imported value. If you're not seeing that then I'm very much at a 
loss. :)

Thanks for putting up with my beginner questions. Maybe I should look 
for a Typescript Differences doc or something. The existing docs seem 
like 90% JS docs, even pitching it as a JS superset, which to me implies 
that it's a drop-in replacement. I'll do a bit more research, 
particularly in the module differences.

**Comment by barbatus** [comment]
If you upload your sample, I'll take a look.

**Comment by ndarilek** [comment]
It's the one linked first in the thread. https://github.com/ndarilek/meteor-typescript-module-resolution-failure/ updated to cause the failure.

**Comment by barbatus** [comment]
Strangely I have only there warnings out of the fresh uploaded repo:
````
server/main.ts (1, 18): Cannot find module 'uuid'.
server/main.ts (5, 1): Cannot find name 'Meteor'.
````

What's you current version of the barbatus:typescript?

Also, you can do just `export * from "./bar"` in the index.ts to avoid unnecessary repeation.

**Comment by ndarilek** [comment]
0.2.1. We should be running on identical versions if you've git pulled 
my sample, since that's in .meteor/versions.

What platform are you on? Wondering if this is somehow Linux-specific.

**Comment by barbatus** [comment]
Mac OS X.
What will happen if you change `./test/index.ts`? it might be related to caching as well.

**Comment by ndarilek** [comment]
Huh, color me confused. I spun this up in a Docker environment and don't 
see the error. Blew away ~/.meteor on my host, still seeing it. 
.meteor/versions on the host and in the container are absolutely 
identical. If this didn't spam my screen with dozens of errors about 
missing modules for code in my own project then I'd just call it harmless.

So I'm officially at a loss. Would like to leave this issue open in case 
anyone else hits it.

FWIW, I'm on Fedora 23 and BTRFS. Doesn't seem like either should be 
relevant, but given we aren't seeing these failures on OS X and in a 
Debian Docker container, and that all other things seem to be equal, I 
don't know what else to suspect. But for the time I think I'll have to 
step back from this unless anyone has any ideas. I don't doubt this 
works for lots of folks but for some reason I'm a unique snowflake. :)

**Comment by barbatus** [comment]
There were multiple bugs fixed with the compilation result cache. Some of them might relate to the current issue. Could you check the status of it?

**Comment by ndarilek** [comment]
Cool.

When I upgrade the test project to 0.2.5, the problems do indeed seem to 
go away. Now I'm getting the expected errors about missing type 
definitions, rather than an error about the missing relative import.

Unfortunately I don't have time to try integrating this into my larger 
project again for the moment, but I'm content to call this closed and 
reopen later should it return.

Thanks.
